# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By:  <@student.42.fr>                          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/28 20:54:40 by                   #+#    #+#              #
#    Updated: 2024/02/28 20:54:40 by                  ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This Makefile was automatically generated by Trillian.
# See the source code to learn more.

NAME = push_swap

DEBUG_LIBFRAMEWORK = /home/bhildebr/github/ft_framework/build/debug/bin/libframework.a
DEFAULT_LIBFRAMEWORK = /home/bhildebr/github/ft_framework/build/default/bin/libframework.a

DEBUG = ./build/debug/bin/push_swap
DEFAULT = ./build/default/bin/push_swap

CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c99 -Dpush_swap=main -g
CPATHS = \
	-include framework.h \
	-include functions.h \
	-include any.h \
	-include cstring.h \
	-include f64.h \
	-include i32.h \
	-include i64.h \
	-include i8.h \
	-include list.h \
	-include map.h \
	-include memtree.h \
	-include type.h \
	-include u32.h \
	-include u64.h \
	-include u8.h \
	-iquote /home/bhildebr/github/ft_framework/source \
	-iquote /home/bhildebr/github/ft_framework/source/functions \
	-iquote /home/bhildebr/github/ft_framework/source/types \
	-iquote /home/bhildebr/github/ft_framework/source/types/any \
	-iquote /home/bhildebr/github/ft_framework/source/types/cstring \
	-iquote /home/bhildebr/github/ft_framework/source/types/f64 \
	-iquote /home/bhildebr/github/ft_framework/source/types/framework \
	-iquote /home/bhildebr/github/ft_framework/source/types/graph \
	-iquote /home/bhildebr/github/ft_framework/source/types/i32 \
	-iquote /home/bhildebr/github/ft_framework/source/types/i64 \
	-iquote /home/bhildebr/github/ft_framework/source/types/i8 \
	-iquote /home/bhildebr/github/ft_framework/source/types/list \
	-iquote /home/bhildebr/github/ft_framework/source/types/map \
	-iquote /home/bhildebr/github/ft_framework/source/types/memtree \
	-iquote /home/bhildebr/github/ft_framework/source/types/type \
	-iquote /home/bhildebr/github/ft_framework/source/types/u32 \
	-iquote /home/bhildebr/github/ft_framework/source/types/u64 \
	-iquote /home/bhildebr/github/ft_framework/source/types/u8 \
	-iquote /home/bhildebr/github/ft_push_swap/source

SOURCES = \
	./source/push_swap.c

HEADERS = 

OBJECTS = \
	push_swap.o

DEPENDENCIES = \
	push_swap.d

TESTS = 

TESTS_OBJECTS = 

TESTS_DEPENDENCIES = 

DEBUG_DIR = ./build/debug
DEFAULT_DIR = ./build/default
TESTS_DIR = ./build/tests

DEBUG_OBJECTS = $(addprefix $(DEBUG_DIR)/objects/, $(OBJECTS))
DEBUG_DEPENDENCIES = $(addprefix $(DEBUG_DIR)/dependencies/, $(DEPENDENCIES))

DEFAULT_OBJECTS = $(addprefix $(DEFAULT_DIR)/objects/, $(OBJECTS))
DEFAULT_DEPENDENCIES = $(addprefix $(DEFAULT_DIR)/dependencies/, $(DEPENDENCIES))

all: build

$(NAME): build

$(DEBUG_LIBFRAMEWORK):
	@make debug -C /home/bhildebr/github/ft_framework

$(DEFAULT_LIBFRAMEWORK):
	@make -C /home/bhildebr/github/ft_framework

debug: $(DEBUG_LIBFRAMEWORK) $(DEBUG)
$(DEBUG): CFLAGS += -DDEBUG -g
$(DEBUG): $(DEBUG_OBJECTS) | $(DEBUG_DIR)
	@$(CC) $(CFLAGS) -o $(DEBUG_DIR)/bin/$(NAME) $(DEBUG_OBJECTS) $(DEBUG_LIBFRAMEWORK)

build: $(DEFAULT_LIBFRAMEWORK) $(DEFAULT)
$(DEFAULT): $(DEFAULT_OBJECTS) | $(DEFAULT_DIR)
	@$(CC) $(CFLAGS) -o $(DEFAULT_DIR)/bin/$(NAME) $(DEFAULT_OBJECTS) $(DEFAULT_LIBFRAMEWORK)

tests: build $(TESTS)
$(TESTS): $(TESTS_OBJECTS) | $(TESTS_DIR)

$(TESTS_OBJECTS): $(DEFAULT_OBJECTS)

clean:
	@$(RM) $(DEBUG_OBJECTS)
	@$(RM) $(DEBUG_DEPENDENCIES)
	@$(RM) $(DEFAULT_OBJECTS)
	@$(RM) $(DEFAULT_DEPENDENCIES)
	@$(RM) $(TESTS_OBJECTS)
	@$(RM) $(TESTS_DEPENDENCIES)

fclean: clean
	@$(RM) $(DEBUG_DIR)/bin/$(NAME)
	@$(RM) $(DEFAULT_DIR)/bin/$(NAME)
	@$(RM) $(TESTS)

re: fclean all

.PHONY: all build debug release $(NAME) clean fclean re

-include $(DEBUG_DEPENDENCIES)
-include $(DEFAULT_DEPENDENCIES)
-include $(TESTS_DEPENDENCIES)

$(DEBUG_DIR)/objects/allocate.o: ./source/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/allocate.d -c ./source/functions/allocate.c -o $(DEBUG_DIR)/objects/allocate.o

$(DEBUG_DIR)/objects/assert.o: ./source/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/assert.d -c ./source/functions/assert.c -o $(DEBUG_DIR)/objects/assert.o

$(DEBUG_DIR)/objects/compare.o: ./source/functions/compare.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/compare.d -c ./source/functions/compare.c -o $(DEBUG_DIR)/objects/compare.o

$(DEBUG_DIR)/objects/copy.o: ./source/functions/copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/copy.d -c ./source/functions/copy.c -o $(DEBUG_DIR)/objects/copy.o

$(DEBUG_DIR)/objects/create.o: ./source/functions/create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/create.d -c ./source/functions/create.c -o $(DEBUG_DIR)/objects/create.o

$(DEBUG_DIR)/objects/deallocate.o: ./source/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/deallocate.d -c ./source/functions/deallocate.c -o $(DEBUG_DIR)/objects/deallocate.o

$(DEBUG_DIR)/objects/debug.o: ./source/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/debug.d -c ./source/functions/debug.c -o $(DEBUG_DIR)/objects/debug.o

$(DEBUG_DIR)/objects/delete.o: ./source/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/delete.d -c ./source/functions/delete.c -o $(DEBUG_DIR)/objects/delete.o

$(DEBUG_DIR)/objects/destroy.o: ./source/functions/destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/destroy.d -c ./source/functions/destroy.c -o $(DEBUG_DIR)/objects/destroy.o

$(DEBUG_DIR)/objects/display.o: ./source/functions/display.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/display.d -c ./source/functions/display.c -o $(DEBUG_DIR)/objects/display.o

$(DEBUG_DIR)/objects/error.o: ./source/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/error.d -c ./source/functions/error.c -o $(DEBUG_DIR)/objects/error.o

$(DEBUG_DIR)/objects/filter.o: ./source/functions/filter.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/filter.d -c ./source/functions/filter.c -o $(DEBUG_DIR)/objects/filter.o

$(DEBUG_DIR)/objects/find.o: ./source/functions/find.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/find.d -c ./source/functions/find.c -o $(DEBUG_DIR)/objects/find.o

$(DEBUG_DIR)/objects/foreach.o: ./source/functions/foreach.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/foreach.d -c ./source/functions/foreach.c -o $(DEBUG_DIR)/objects/foreach.o

$(DEBUG_DIR)/objects/forkrun.o: ./source/functions/forkrun.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/forkrun.d -c ./source/functions/forkrun.c -o $(DEBUG_DIR)/objects/forkrun.o

$(DEBUG_DIR)/objects/getg.o: ./source/functions/getg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/getg.d -c ./source/functions/getg.c -o $(DEBUG_DIR)/objects/getg.o

$(DEBUG_DIR)/objects/init.o: ./source/functions/init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/init.d -c ./source/functions/init.c -o $(DEBUG_DIR)/objects/init.o

$(DEBUG_DIR)/objects/new.o: ./source/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/new.d -c ./source/functions/new.c -o $(DEBUG_DIR)/objects/new.o

$(DEBUG_DIR)/objects/print.o: ./source/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/print.d -c ./source/functions/print.c -o $(DEBUG_DIR)/objects/print.o

$(DEBUG_DIR)/objects/push.o: ./source/functions/push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/push.d -c ./source/functions/push.c -o $(DEBUG_DIR)/objects/push.o

$(DEBUG_DIR)/objects/quit.o: ./source/functions/quit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/quit.d -c ./source/functions/quit.c -o $(DEBUG_DIR)/objects/quit.o

$(DEBUG_DIR)/objects/range.o: ./source/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/range.d -c ./source/functions/range.c -o $(DEBUG_DIR)/objects/range.o

$(DEBUG_DIR)/objects/reduce.o: ./source/functions/reduce.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/reduce.d -c ./source/functions/reduce.c -o $(DEBUG_DIR)/objects/reduce.o

$(DEBUG_DIR)/objects/repeat.o: ./source/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/repeat.d -c ./source/functions/repeat.c -o $(DEBUG_DIR)/objects/repeat.o

$(DEBUG_DIR)/objects/setg.o: ./source/functions/setg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/setg.d -c ./source/functions/setg.c -o $(DEBUG_DIR)/objects/setg.o

$(DEBUG_DIR)/objects/slice.o: ./source/functions/slice.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/slice.d -c ./source/functions/slice.c -o $(DEBUG_DIR)/objects/slice.o

$(DEBUG_DIR)/objects/warning.o: ./source/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/warning.d -c ./source/functions/warning.c -o $(DEBUG_DIR)/objects/warning.o

$(DEBUG_DIR)/objects/any.o: ./source/types/any/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any.d -c ./source/types/any/any.c -o $(DEBUG_DIR)/objects/any.o

$(DEBUG_DIR)/objects/any_copy.o: ./source/types/any/any_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_copy.d -c ./source/types/any/any_copy.c -o $(DEBUG_DIR)/objects/any_copy.o

$(DEBUG_DIR)/objects/any_create.o: ./source/types/any/any_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_create.d -c ./source/types/any/any_create.c -o $(DEBUG_DIR)/objects/any_create.o

$(DEBUG_DIR)/objects/any_destroy.o: ./source/types/any/any_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_destroy.d -c ./source/types/any/any_destroy.c -o $(DEBUG_DIR)/objects/any_destroy.o

$(DEBUG_DIR)/objects/any_to_cstring.o: ./source/types/any/any_to_cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_cstring.d -c ./source/types/any/any_to_cstring.c -o $(DEBUG_DIR)/objects/any_to_cstring.o

$(DEBUG_DIR)/objects/any_to_f64.o: ./source/types/any/any_to_f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_f64.d -c ./source/types/any/any_to_f64.c -o $(DEBUG_DIR)/objects/any_to_f64.o

$(DEBUG_DIR)/objects/any_to_i32.o: ./source/types/any/any_to_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_i32.d -c ./source/types/any/any_to_i32.c -o $(DEBUG_DIR)/objects/any_to_i32.o

$(DEBUG_DIR)/objects/any_to_i64.o: ./source/types/any/any_to_i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_i64.d -c ./source/types/any/any_to_i64.c -o $(DEBUG_DIR)/objects/any_to_i64.o

$(DEBUG_DIR)/objects/any_to_i8.o: ./source/types/any/any_to_i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_i8.d -c ./source/types/any/any_to_i8.c -o $(DEBUG_DIR)/objects/any_to_i8.o

$(DEBUG_DIR)/objects/any_to_instance.o: ./source/types/any/any_to_instance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_instance.d -c ./source/types/any/any_to_instance.c -o $(DEBUG_DIR)/objects/any_to_instance.o

$(DEBUG_DIR)/objects/any_to_u32.o: ./source/types/any/any_to_u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_u32.d -c ./source/types/any/any_to_u32.c -o $(DEBUG_DIR)/objects/any_to_u32.o

$(DEBUG_DIR)/objects/any_to_u64.o: ./source/types/any/any_to_u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_u64.d -c ./source/types/any/any_to_u64.c -o $(DEBUG_DIR)/objects/any_to_u64.o

$(DEBUG_DIR)/objects/any_to_u8.o: ./source/types/any/any_to_u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/any_to_u8.d -c ./source/types/any/any_to_u8.c -o $(DEBUG_DIR)/objects/any_to_u8.o

$(DEBUG_DIR)/objects/cstring.o: ./source/types/cstring/cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cstring.d -c ./source/types/cstring/cstring.c -o $(DEBUG_DIR)/objects/cstring.o

$(DEBUG_DIR)/objects/cstring_is_i32.o: ./source/types/cstring/cstring_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cstring_is_i32.d -c ./source/types/cstring/cstring_is_i32.c -o $(DEBUG_DIR)/objects/cstring_is_i32.o

$(DEBUG_DIR)/objects/cstring_to_any.o: ./source/types/cstring/cstring_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/cstring_to_any.d -c ./source/types/cstring/cstring_to_any.c -o $(DEBUG_DIR)/objects/cstring_to_any.o

$(DEBUG_DIR)/objects/f64.o: ./source/types/f64/f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/f64.d -c ./source/types/f64/f64.c -o $(DEBUG_DIR)/objects/f64.o

$(DEBUG_DIR)/objects/f64_to_any.o: ./source/types/f64/f64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/f64_to_any.d -c ./source/types/f64/f64_to_any.c -o $(DEBUG_DIR)/objects/f64_to_any.o

$(DEBUG_DIR)/objects/framework_get.o: ./source/types/framework/framework_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get.d -c ./source/types/framework/framework_get.c -o $(DEBUG_DIR)/objects/framework_get.o

$(DEBUG_DIR)/objects/framework_get_map.o: ./source/types/framework/framework_get_map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get_map.d -c ./source/types/framework/framework_get_map.c -o $(DEBUG_DIR)/objects/framework_get_map.o

$(DEBUG_DIR)/objects/framework_get_memtree.o: ./source/types/framework/framework_get_memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/framework_get_memtree.d -c ./source/types/framework/framework_get_memtree.c -o $(DEBUG_DIR)/objects/framework_get_memtree.o

$(DEBUG_DIR)/objects/i32.o: ./source/types/i32/i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i32.d -c ./source/types/i32/i32.c -o $(DEBUG_DIR)/objects/i32.o

$(DEBUG_DIR)/objects/i32_to_any.o: ./source/types/i32/i32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i32_to_any.d -c ./source/types/i32/i32_to_any.c -o $(DEBUG_DIR)/objects/i32_to_any.o

$(DEBUG_DIR)/objects/i64.o: ./source/types/i64/i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i64.d -c ./source/types/i64/i64.c -o $(DEBUG_DIR)/objects/i64.o

$(DEBUG_DIR)/objects/i64_is_i32.o: ./source/types/i64/i64_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i64_is_i32.d -c ./source/types/i64/i64_is_i32.c -o $(DEBUG_DIR)/objects/i64_is_i32.o

$(DEBUG_DIR)/objects/i64_to_any.o: ./source/types/i64/i64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i64_to_any.d -c ./source/types/i64/i64_to_any.c -o $(DEBUG_DIR)/objects/i64_to_any.o

$(DEBUG_DIR)/objects/i8.o: ./source/types/i8/i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8.d -c ./source/types/i8/i8.c -o $(DEBUG_DIR)/objects/i8.o

$(DEBUG_DIR)/objects/i8_is_digit.o: ./source/types/i8/i8_is_digit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_is_digit.d -c ./source/types/i8/i8_is_digit.c -o $(DEBUG_DIR)/objects/i8_is_digit.o

$(DEBUG_DIR)/objects/i8_is_signal.o: ./source/types/i8/i8_is_signal.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_is_signal.d -c ./source/types/i8/i8_is_signal.c -o $(DEBUG_DIR)/objects/i8_is_signal.o

$(DEBUG_DIR)/objects/i8_is_space.o: ./source/types/i8/i8_is_space.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_is_space.d -c ./source/types/i8/i8_is_space.c -o $(DEBUG_DIR)/objects/i8_is_space.o

$(DEBUG_DIR)/objects/i8_to_any.o: ./source/types/i8/i8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/i8_to_any.d -c ./source/types/i8/i8_to_any.c -o $(DEBUG_DIR)/objects/i8_to_any.o

$(DEBUG_DIR)/objects/list.o: ./source/types/list/list.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list.d -c ./source/types/list/list.c -o $(DEBUG_DIR)/objects/list.o

$(DEBUG_DIR)/objects/list_copy.o: ./source/types/list/list_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_copy.d -c ./source/types/list/list_copy.c -o $(DEBUG_DIR)/objects/list_copy.o

$(DEBUG_DIR)/objects/list_create.o: ./source/types/list/list_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_create.d -c ./source/types/list/list_create.c -o $(DEBUG_DIR)/objects/list_create.o

$(DEBUG_DIR)/objects/list_destroy.o: ./source/types/list/list_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_destroy.d -c ./source/types/list/list_destroy.c -o $(DEBUG_DIR)/objects/list_destroy.o

$(DEBUG_DIR)/objects/list_expand.o: ./source/types/list/list_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_expand.d -c ./source/types/list/list_expand.c -o $(DEBUG_DIR)/objects/list_expand.o

$(DEBUG_DIR)/objects/list_get.o: ./source/types/list/list_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_get.d -c ./source/types/list/list_get.c -o $(DEBUG_DIR)/objects/list_get.o

$(DEBUG_DIR)/objects/list_get_length.o: ./source/types/list/list_get_length.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_get_length.d -c ./source/types/list/list_get_length.c -o $(DEBUG_DIR)/objects/list_get_length.o

$(DEBUG_DIR)/objects/list_pop.o: ./source/types/list/list_pop.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_pop.d -c ./source/types/list/list_pop.c -o $(DEBUG_DIR)/objects/list_pop.o

$(DEBUG_DIR)/objects/list_push.o: ./source/types/list/list_push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_push.d -c ./source/types/list/list_push.c -o $(DEBUG_DIR)/objects/list_push.o

$(DEBUG_DIR)/objects/list_reverse.o: ./source/types/list/list_reverse.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_reverse.d -c ./source/types/list/list_reverse.c -o $(DEBUG_DIR)/objects/list_reverse.o

$(DEBUG_DIR)/objects/list_set.o: ./source/types/list/list_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_set.d -c ./source/types/list/list_set.c -o $(DEBUG_DIR)/objects/list_set.o

$(DEBUG_DIR)/objects/list_shift.o: ./source/types/list/list_shift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_shift.d -c ./source/types/list/list_shift.c -o $(DEBUG_DIR)/objects/list_shift.o

$(DEBUG_DIR)/objects/list_to_any.o: ./source/types/list/list_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_to_any.d -c ./source/types/list/list_to_any.c -o $(DEBUG_DIR)/objects/list_to_any.o

$(DEBUG_DIR)/objects/list_unshift.o: ./source/types/list/list_unshift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/list_unshift.d -c ./source/types/list/list_unshift.c -o $(DEBUG_DIR)/objects/list_unshift.o

$(DEBUG_DIR)/objects/map.o: ./source/types/map/map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map.d -c ./source/types/map/map.c -o $(DEBUG_DIR)/objects/map.o

$(DEBUG_DIR)/objects/map_copy.o: ./source/types/map/map_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_copy.d -c ./source/types/map/map_copy.c -o $(DEBUG_DIR)/objects/map_copy.o

$(DEBUG_DIR)/objects/map_create.o: ./source/types/map/map_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_create.d -c ./source/types/map/map_create.c -o $(DEBUG_DIR)/objects/map_create.o

$(DEBUG_DIR)/objects/map_destroy.o: ./source/types/map/map_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_destroy.d -c ./source/types/map/map_destroy.c -o $(DEBUG_DIR)/objects/map_destroy.o

$(DEBUG_DIR)/objects/map_expand.o: ./source/types/map/map_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_expand.d -c ./source/types/map/map_expand.c -o $(DEBUG_DIR)/objects/map_expand.o

$(DEBUG_DIR)/objects/map_get.o: ./source/types/map/map_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_get.d -c ./source/types/map/map_get.c -o $(DEBUG_DIR)/objects/map_get.o

$(DEBUG_DIR)/objects/map_hash.o: ./source/types/map/map_hash.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_hash.d -c ./source/types/map/map_hash.c -o $(DEBUG_DIR)/objects/map_hash.o

$(DEBUG_DIR)/objects/map_set.o: ./source/types/map/map_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/map_set.d -c ./source/types/map/map_set.c -o $(DEBUG_DIR)/objects/map_set.o

$(DEBUG_DIR)/objects/memtree_create.o: ./source/types/memtree/memtree_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_create.d -c ./source/types/memtree/memtree_create.c -o $(DEBUG_DIR)/objects/memtree_create.o

$(DEBUG_DIR)/objects/memtree_delete.o: ./source/types/memtree/memtree_delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_delete.d -c ./source/types/memtree/memtree_delete.c -o $(DEBUG_DIR)/objects/memtree_delete.o

$(DEBUG_DIR)/objects/memtree_destroy.o: ./source/types/memtree/memtree_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_destroy.d -c ./source/types/memtree/memtree_destroy.c -o $(DEBUG_DIR)/objects/memtree_destroy.o

$(DEBUG_DIR)/objects/memtree_get.o: ./source/types/memtree/memtree_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_get.d -c ./source/types/memtree/memtree_get.c -o $(DEBUG_DIR)/objects/memtree_get.o

$(DEBUG_DIR)/objects/memtree_get_height.o: ./source/types/memtree/memtree_get_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_get_height.d -c ./source/types/memtree/memtree_get_height.c -o $(DEBUG_DIR)/objects/memtree_get_height.o

$(DEBUG_DIR)/objects/memtree_insert.o: ./source/types/memtree/memtree_insert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_insert.d -c ./source/types/memtree/memtree_insert.c -o $(DEBUG_DIR)/objects/memtree_insert.o

$(DEBUG_DIR)/objects/memtree_print.o: ./source/types/memtree/memtree_print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_print.d -c ./source/types/memtree/memtree_print.c -o $(DEBUG_DIR)/objects/memtree_print.o

$(DEBUG_DIR)/objects/memtree_rebalance.o: ./source/types/memtree/memtree_rebalance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_rebalance.d -c ./source/types/memtree/memtree_rebalance.c -o $(DEBUG_DIR)/objects/memtree_rebalance.o

$(DEBUG_DIR)/objects/memtree_search.o: ./source/types/memtree/memtree_search.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_search.d -c ./source/types/memtree/memtree_search.c -o $(DEBUG_DIR)/objects/memtree_search.o

$(DEBUG_DIR)/objects/memtree_update_height.o: ./source/types/memtree/memtree_update_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/memtree_update_height.d -c ./source/types/memtree/memtree_update_height.c -o $(DEBUG_DIR)/objects/memtree_update_height.o

$(DEBUG_DIR)/objects/u32.o: ./source/types/u32/u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u32.d -c ./source/types/u32/u32.c -o $(DEBUG_DIR)/objects/u32.o

$(DEBUG_DIR)/objects/u32_to_any.o: ./source/types/u32/u32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u32_to_any.d -c ./source/types/u32/u32_to_any.c -o $(DEBUG_DIR)/objects/u32_to_any.o

$(DEBUG_DIR)/objects/u64.o: ./source/types/u64/u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u64.d -c ./source/types/u64/u64.c -o $(DEBUG_DIR)/objects/u64.o

$(DEBUG_DIR)/objects/u64_to_any.o: ./source/types/u64/u64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u64_to_any.d -c ./source/types/u64/u64_to_any.c -o $(DEBUG_DIR)/objects/u64_to_any.o

$(DEBUG_DIR)/objects/u8.o: ./source/types/u8/u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u8.d -c ./source/types/u8/u8.c -o $(DEBUG_DIR)/objects/u8.o

$(DEBUG_DIR)/objects/u8_to_any.o: ./source/types/u8/u8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/u8_to_any.d -c ./source/types/u8/u8_to_any.c -o $(DEBUG_DIR)/objects/u8_to_any.o

$(DEBUG_DIR)/objects/push_swap.o: ./source/push_swap.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEBUG_DIR)/dependencies/push_swap.d -c ./source/push_swap.c -o $(DEBUG_DIR)/objects/push_swap.o


$(DEFAULT_DIR)/objects/allocate.o: ./source/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/allocate.d -c ./source/functions/allocate.c -o $(DEFAULT_DIR)/objects/allocate.o

$(DEFAULT_DIR)/objects/assert.o: ./source/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/assert.d -c ./source/functions/assert.c -o $(DEFAULT_DIR)/objects/assert.o

$(DEFAULT_DIR)/objects/compare.o: ./source/functions/compare.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/compare.d -c ./source/functions/compare.c -o $(DEFAULT_DIR)/objects/compare.o

$(DEFAULT_DIR)/objects/copy.o: ./source/functions/copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/copy.d -c ./source/functions/copy.c -o $(DEFAULT_DIR)/objects/copy.o

$(DEFAULT_DIR)/objects/create.o: ./source/functions/create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/create.d -c ./source/functions/create.c -o $(DEFAULT_DIR)/objects/create.o

$(DEFAULT_DIR)/objects/deallocate.o: ./source/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/deallocate.d -c ./source/functions/deallocate.c -o $(DEFAULT_DIR)/objects/deallocate.o

$(DEFAULT_DIR)/objects/debug.o: ./source/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/debug.d -c ./source/functions/debug.c -o $(DEFAULT_DIR)/objects/debug.o

$(DEFAULT_DIR)/objects/delete.o: ./source/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/delete.d -c ./source/functions/delete.c -o $(DEFAULT_DIR)/objects/delete.o

$(DEFAULT_DIR)/objects/destroy.o: ./source/functions/destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/destroy.d -c ./source/functions/destroy.c -o $(DEFAULT_DIR)/objects/destroy.o

$(DEFAULT_DIR)/objects/display.o: ./source/functions/display.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/display.d -c ./source/functions/display.c -o $(DEFAULT_DIR)/objects/display.o

$(DEFAULT_DIR)/objects/error.o: ./source/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/error.d -c ./source/functions/error.c -o $(DEFAULT_DIR)/objects/error.o

$(DEFAULT_DIR)/objects/filter.o: ./source/functions/filter.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/filter.d -c ./source/functions/filter.c -o $(DEFAULT_DIR)/objects/filter.o

$(DEFAULT_DIR)/objects/find.o: ./source/functions/find.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/find.d -c ./source/functions/find.c -o $(DEFAULT_DIR)/objects/find.o

$(DEFAULT_DIR)/objects/foreach.o: ./source/functions/foreach.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/foreach.d -c ./source/functions/foreach.c -o $(DEFAULT_DIR)/objects/foreach.o

$(DEFAULT_DIR)/objects/forkrun.o: ./source/functions/forkrun.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/forkrun.d -c ./source/functions/forkrun.c -o $(DEFAULT_DIR)/objects/forkrun.o

$(DEFAULT_DIR)/objects/getg.o: ./source/functions/getg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/getg.d -c ./source/functions/getg.c -o $(DEFAULT_DIR)/objects/getg.o

$(DEFAULT_DIR)/objects/init.o: ./source/functions/init.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/init.d -c ./source/functions/init.c -o $(DEFAULT_DIR)/objects/init.o

$(DEFAULT_DIR)/objects/new.o: ./source/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/new.d -c ./source/functions/new.c -o $(DEFAULT_DIR)/objects/new.o

$(DEFAULT_DIR)/objects/print.o: ./source/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/print.d -c ./source/functions/print.c -o $(DEFAULT_DIR)/objects/print.o

$(DEFAULT_DIR)/objects/push.o: ./source/functions/push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/push.d -c ./source/functions/push.c -o $(DEFAULT_DIR)/objects/push.o

$(DEFAULT_DIR)/objects/quit.o: ./source/functions/quit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/quit.d -c ./source/functions/quit.c -o $(DEFAULT_DIR)/objects/quit.o

$(DEFAULT_DIR)/objects/range.o: ./source/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/range.d -c ./source/functions/range.c -o $(DEFAULT_DIR)/objects/range.o

$(DEFAULT_DIR)/objects/reduce.o: ./source/functions/reduce.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/reduce.d -c ./source/functions/reduce.c -o $(DEFAULT_DIR)/objects/reduce.o

$(DEFAULT_DIR)/objects/repeat.o: ./source/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/repeat.d -c ./source/functions/repeat.c -o $(DEFAULT_DIR)/objects/repeat.o

$(DEFAULT_DIR)/objects/setg.o: ./source/functions/setg.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/setg.d -c ./source/functions/setg.c -o $(DEFAULT_DIR)/objects/setg.o

$(DEFAULT_DIR)/objects/slice.o: ./source/functions/slice.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/slice.d -c ./source/functions/slice.c -o $(DEFAULT_DIR)/objects/slice.o

$(DEFAULT_DIR)/objects/warning.o: ./source/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/warning.d -c ./source/functions/warning.c -o $(DEFAULT_DIR)/objects/warning.o

$(DEFAULT_DIR)/objects/any.o: ./source/types/any/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any.d -c ./source/types/any/any.c -o $(DEFAULT_DIR)/objects/any.o

$(DEFAULT_DIR)/objects/any_copy.o: ./source/types/any/any_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_copy.d -c ./source/types/any/any_copy.c -o $(DEFAULT_DIR)/objects/any_copy.o

$(DEFAULT_DIR)/objects/any_create.o: ./source/types/any/any_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_create.d -c ./source/types/any/any_create.c -o $(DEFAULT_DIR)/objects/any_create.o

$(DEFAULT_DIR)/objects/any_destroy.o: ./source/types/any/any_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_destroy.d -c ./source/types/any/any_destroy.c -o $(DEFAULT_DIR)/objects/any_destroy.o

$(DEFAULT_DIR)/objects/any_to_cstring.o: ./source/types/any/any_to_cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_cstring.d -c ./source/types/any/any_to_cstring.c -o $(DEFAULT_DIR)/objects/any_to_cstring.o

$(DEFAULT_DIR)/objects/any_to_f64.o: ./source/types/any/any_to_f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_f64.d -c ./source/types/any/any_to_f64.c -o $(DEFAULT_DIR)/objects/any_to_f64.o

$(DEFAULT_DIR)/objects/any_to_i32.o: ./source/types/any/any_to_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_i32.d -c ./source/types/any/any_to_i32.c -o $(DEFAULT_DIR)/objects/any_to_i32.o

$(DEFAULT_DIR)/objects/any_to_i64.o: ./source/types/any/any_to_i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_i64.d -c ./source/types/any/any_to_i64.c -o $(DEFAULT_DIR)/objects/any_to_i64.o

$(DEFAULT_DIR)/objects/any_to_i8.o: ./source/types/any/any_to_i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_i8.d -c ./source/types/any/any_to_i8.c -o $(DEFAULT_DIR)/objects/any_to_i8.o

$(DEFAULT_DIR)/objects/any_to_instance.o: ./source/types/any/any_to_instance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_instance.d -c ./source/types/any/any_to_instance.c -o $(DEFAULT_DIR)/objects/any_to_instance.o

$(DEFAULT_DIR)/objects/any_to_u32.o: ./source/types/any/any_to_u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_u32.d -c ./source/types/any/any_to_u32.c -o $(DEFAULT_DIR)/objects/any_to_u32.o

$(DEFAULT_DIR)/objects/any_to_u64.o: ./source/types/any/any_to_u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_u64.d -c ./source/types/any/any_to_u64.c -o $(DEFAULT_DIR)/objects/any_to_u64.o

$(DEFAULT_DIR)/objects/any_to_u8.o: ./source/types/any/any_to_u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/any_to_u8.d -c ./source/types/any/any_to_u8.c -o $(DEFAULT_DIR)/objects/any_to_u8.o

$(DEFAULT_DIR)/objects/cstring.o: ./source/types/cstring/cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cstring.d -c ./source/types/cstring/cstring.c -o $(DEFAULT_DIR)/objects/cstring.o

$(DEFAULT_DIR)/objects/cstring_is_i32.o: ./source/types/cstring/cstring_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cstring_is_i32.d -c ./source/types/cstring/cstring_is_i32.c -o $(DEFAULT_DIR)/objects/cstring_is_i32.o

$(DEFAULT_DIR)/objects/cstring_to_any.o: ./source/types/cstring/cstring_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/cstring_to_any.d -c ./source/types/cstring/cstring_to_any.c -o $(DEFAULT_DIR)/objects/cstring_to_any.o

$(DEFAULT_DIR)/objects/f64.o: ./source/types/f64/f64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/f64.d -c ./source/types/f64/f64.c -o $(DEFAULT_DIR)/objects/f64.o

$(DEFAULT_DIR)/objects/f64_to_any.o: ./source/types/f64/f64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/f64_to_any.d -c ./source/types/f64/f64_to_any.c -o $(DEFAULT_DIR)/objects/f64_to_any.o

$(DEFAULT_DIR)/objects/framework_get.o: ./source/types/framework/framework_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get.d -c ./source/types/framework/framework_get.c -o $(DEFAULT_DIR)/objects/framework_get.o

$(DEFAULT_DIR)/objects/framework_get_map.o: ./source/types/framework/framework_get_map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get_map.d -c ./source/types/framework/framework_get_map.c -o $(DEFAULT_DIR)/objects/framework_get_map.o

$(DEFAULT_DIR)/objects/framework_get_memtree.o: ./source/types/framework/framework_get_memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/framework_get_memtree.d -c ./source/types/framework/framework_get_memtree.c -o $(DEFAULT_DIR)/objects/framework_get_memtree.o

$(DEFAULT_DIR)/objects/i32.o: ./source/types/i32/i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i32.d -c ./source/types/i32/i32.c -o $(DEFAULT_DIR)/objects/i32.o

$(DEFAULT_DIR)/objects/i32_to_any.o: ./source/types/i32/i32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i32_to_any.d -c ./source/types/i32/i32_to_any.c -o $(DEFAULT_DIR)/objects/i32_to_any.o

$(DEFAULT_DIR)/objects/i64.o: ./source/types/i64/i64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i64.d -c ./source/types/i64/i64.c -o $(DEFAULT_DIR)/objects/i64.o

$(DEFAULT_DIR)/objects/i64_is_i32.o: ./source/types/i64/i64_is_i32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i64_is_i32.d -c ./source/types/i64/i64_is_i32.c -o $(DEFAULT_DIR)/objects/i64_is_i32.o

$(DEFAULT_DIR)/objects/i64_to_any.o: ./source/types/i64/i64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i64_to_any.d -c ./source/types/i64/i64_to_any.c -o $(DEFAULT_DIR)/objects/i64_to_any.o

$(DEFAULT_DIR)/objects/i8.o: ./source/types/i8/i8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8.d -c ./source/types/i8/i8.c -o $(DEFAULT_DIR)/objects/i8.o

$(DEFAULT_DIR)/objects/i8_is_digit.o: ./source/types/i8/i8_is_digit.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_is_digit.d -c ./source/types/i8/i8_is_digit.c -o $(DEFAULT_DIR)/objects/i8_is_digit.o

$(DEFAULT_DIR)/objects/i8_is_signal.o: ./source/types/i8/i8_is_signal.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_is_signal.d -c ./source/types/i8/i8_is_signal.c -o $(DEFAULT_DIR)/objects/i8_is_signal.o

$(DEFAULT_DIR)/objects/i8_is_space.o: ./source/types/i8/i8_is_space.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_is_space.d -c ./source/types/i8/i8_is_space.c -o $(DEFAULT_DIR)/objects/i8_is_space.o

$(DEFAULT_DIR)/objects/i8_to_any.o: ./source/types/i8/i8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/i8_to_any.d -c ./source/types/i8/i8_to_any.c -o $(DEFAULT_DIR)/objects/i8_to_any.o

$(DEFAULT_DIR)/objects/list.o: ./source/types/list/list.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list.d -c ./source/types/list/list.c -o $(DEFAULT_DIR)/objects/list.o

$(DEFAULT_DIR)/objects/list_copy.o: ./source/types/list/list_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_copy.d -c ./source/types/list/list_copy.c -o $(DEFAULT_DIR)/objects/list_copy.o

$(DEFAULT_DIR)/objects/list_create.o: ./source/types/list/list_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_create.d -c ./source/types/list/list_create.c -o $(DEFAULT_DIR)/objects/list_create.o

$(DEFAULT_DIR)/objects/list_destroy.o: ./source/types/list/list_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_destroy.d -c ./source/types/list/list_destroy.c -o $(DEFAULT_DIR)/objects/list_destroy.o

$(DEFAULT_DIR)/objects/list_expand.o: ./source/types/list/list_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_expand.d -c ./source/types/list/list_expand.c -o $(DEFAULT_DIR)/objects/list_expand.o

$(DEFAULT_DIR)/objects/list_get.o: ./source/types/list/list_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_get.d -c ./source/types/list/list_get.c -o $(DEFAULT_DIR)/objects/list_get.o

$(DEFAULT_DIR)/objects/list_get_length.o: ./source/types/list/list_get_length.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_get_length.d -c ./source/types/list/list_get_length.c -o $(DEFAULT_DIR)/objects/list_get_length.o

$(DEFAULT_DIR)/objects/list_pop.o: ./source/types/list/list_pop.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_pop.d -c ./source/types/list/list_pop.c -o $(DEFAULT_DIR)/objects/list_pop.o

$(DEFAULT_DIR)/objects/list_push.o: ./source/types/list/list_push.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_push.d -c ./source/types/list/list_push.c -o $(DEFAULT_DIR)/objects/list_push.o

$(DEFAULT_DIR)/objects/list_reverse.o: ./source/types/list/list_reverse.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_reverse.d -c ./source/types/list/list_reverse.c -o $(DEFAULT_DIR)/objects/list_reverse.o

$(DEFAULT_DIR)/objects/list_set.o: ./source/types/list/list_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_set.d -c ./source/types/list/list_set.c -o $(DEFAULT_DIR)/objects/list_set.o

$(DEFAULT_DIR)/objects/list_shift.o: ./source/types/list/list_shift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_shift.d -c ./source/types/list/list_shift.c -o $(DEFAULT_DIR)/objects/list_shift.o

$(DEFAULT_DIR)/objects/list_to_any.o: ./source/types/list/list_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_to_any.d -c ./source/types/list/list_to_any.c -o $(DEFAULT_DIR)/objects/list_to_any.o

$(DEFAULT_DIR)/objects/list_unshift.o: ./source/types/list/list_unshift.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/list_unshift.d -c ./source/types/list/list_unshift.c -o $(DEFAULT_DIR)/objects/list_unshift.o

$(DEFAULT_DIR)/objects/map.o: ./source/types/map/map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map.d -c ./source/types/map/map.c -o $(DEFAULT_DIR)/objects/map.o

$(DEFAULT_DIR)/objects/map_copy.o: ./source/types/map/map_copy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_copy.d -c ./source/types/map/map_copy.c -o $(DEFAULT_DIR)/objects/map_copy.o

$(DEFAULT_DIR)/objects/map_create.o: ./source/types/map/map_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_create.d -c ./source/types/map/map_create.c -o $(DEFAULT_DIR)/objects/map_create.o

$(DEFAULT_DIR)/objects/map_destroy.o: ./source/types/map/map_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_destroy.d -c ./source/types/map/map_destroy.c -o $(DEFAULT_DIR)/objects/map_destroy.o

$(DEFAULT_DIR)/objects/map_expand.o: ./source/types/map/map_expand.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_expand.d -c ./source/types/map/map_expand.c -o $(DEFAULT_DIR)/objects/map_expand.o

$(DEFAULT_DIR)/objects/map_get.o: ./source/types/map/map_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_get.d -c ./source/types/map/map_get.c -o $(DEFAULT_DIR)/objects/map_get.o

$(DEFAULT_DIR)/objects/map_hash.o: ./source/types/map/map_hash.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_hash.d -c ./source/types/map/map_hash.c -o $(DEFAULT_DIR)/objects/map_hash.o

$(DEFAULT_DIR)/objects/map_set.o: ./source/types/map/map_set.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/map_set.d -c ./source/types/map/map_set.c -o $(DEFAULT_DIR)/objects/map_set.o

$(DEFAULT_DIR)/objects/memtree_create.o: ./source/types/memtree/memtree_create.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_create.d -c ./source/types/memtree/memtree_create.c -o $(DEFAULT_DIR)/objects/memtree_create.o

$(DEFAULT_DIR)/objects/memtree_delete.o: ./source/types/memtree/memtree_delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_delete.d -c ./source/types/memtree/memtree_delete.c -o $(DEFAULT_DIR)/objects/memtree_delete.o

$(DEFAULT_DIR)/objects/memtree_destroy.o: ./source/types/memtree/memtree_destroy.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_destroy.d -c ./source/types/memtree/memtree_destroy.c -o $(DEFAULT_DIR)/objects/memtree_destroy.o

$(DEFAULT_DIR)/objects/memtree_get.o: ./source/types/memtree/memtree_get.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_get.d -c ./source/types/memtree/memtree_get.c -o $(DEFAULT_DIR)/objects/memtree_get.o

$(DEFAULT_DIR)/objects/memtree_get_height.o: ./source/types/memtree/memtree_get_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_get_height.d -c ./source/types/memtree/memtree_get_height.c -o $(DEFAULT_DIR)/objects/memtree_get_height.o

$(DEFAULT_DIR)/objects/memtree_insert.o: ./source/types/memtree/memtree_insert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_insert.d -c ./source/types/memtree/memtree_insert.c -o $(DEFAULT_DIR)/objects/memtree_insert.o

$(DEFAULT_DIR)/objects/memtree_print.o: ./source/types/memtree/memtree_print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_print.d -c ./source/types/memtree/memtree_print.c -o $(DEFAULT_DIR)/objects/memtree_print.o

$(DEFAULT_DIR)/objects/memtree_rebalance.o: ./source/types/memtree/memtree_rebalance.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_rebalance.d -c ./source/types/memtree/memtree_rebalance.c -o $(DEFAULT_DIR)/objects/memtree_rebalance.o

$(DEFAULT_DIR)/objects/memtree_search.o: ./source/types/memtree/memtree_search.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_search.d -c ./source/types/memtree/memtree_search.c -o $(DEFAULT_DIR)/objects/memtree_search.o

$(DEFAULT_DIR)/objects/memtree_update_height.o: ./source/types/memtree/memtree_update_height.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/memtree_update_height.d -c ./source/types/memtree/memtree_update_height.c -o $(DEFAULT_DIR)/objects/memtree_update_height.o

$(DEFAULT_DIR)/objects/u32.o: ./source/types/u32/u32.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u32.d -c ./source/types/u32/u32.c -o $(DEFAULT_DIR)/objects/u32.o

$(DEFAULT_DIR)/objects/u32_to_any.o: ./source/types/u32/u32_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u32_to_any.d -c ./source/types/u32/u32_to_any.c -o $(DEFAULT_DIR)/objects/u32_to_any.o

$(DEFAULT_DIR)/objects/u64.o: ./source/types/u64/u64.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u64.d -c ./source/types/u64/u64.c -o $(DEFAULT_DIR)/objects/u64.o

$(DEFAULT_DIR)/objects/u64_to_any.o: ./source/types/u64/u64_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u64_to_any.d -c ./source/types/u64/u64_to_any.c -o $(DEFAULT_DIR)/objects/u64_to_any.o

$(DEFAULT_DIR)/objects/u8.o: ./source/types/u8/u8.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u8.d -c ./source/types/u8/u8.c -o $(DEFAULT_DIR)/objects/u8.o

$(DEFAULT_DIR)/objects/u8_to_any.o: ./source/types/u8/u8_to_any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/u8_to_any.d -c ./source/types/u8/u8_to_any.c -o $(DEFAULT_DIR)/objects/u8_to_any.o

$(DEFAULT_DIR)/objects/push_swap.o: ./source/push_swap.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(DEFAULT_DIR)/dependencies/push_swap.d -c ./source/push_swap.c -o $(DEFAULT_DIR)/objects/push_swap.o


$(TESTS_DIR)/objects/allocate.o: ./tests/functions/allocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/allocate.d -c ./tests/functions/allocate.c -o $(TESTS_DIR)/objects/allocate.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/allocate.o $(DEFAULT) -o $(TESTS_DIR)/bin/allocate

$(TESTS_DIR)/objects/assert.o: ./tests/functions/assert.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/assert.d -c ./tests/functions/assert.c -o $(TESTS_DIR)/objects/assert.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/assert.o $(DEFAULT) -o $(TESTS_DIR)/bin/assert

$(TESTS_DIR)/objects/deallocate.o: ./tests/functions/deallocate.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/deallocate.d -c ./tests/functions/deallocate.c -o $(TESTS_DIR)/objects/deallocate.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/deallocate.o $(DEFAULT) -o $(TESTS_DIR)/bin/deallocate

$(TESTS_DIR)/objects/debug.o: ./tests/functions/debug.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/debug.d -c ./tests/functions/debug.c -o $(TESTS_DIR)/objects/debug.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/debug.o $(DEFAULT) -o $(TESTS_DIR)/bin/debug

$(TESTS_DIR)/objects/delete.o: ./tests/functions/delete.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/delete.d -c ./tests/functions/delete.c -o $(TESTS_DIR)/objects/delete.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/delete.o $(DEFAULT) -o $(TESTS_DIR)/bin/delete

$(TESTS_DIR)/objects/error.o: ./tests/functions/error.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/error.d -c ./tests/functions/error.c -o $(TESTS_DIR)/objects/error.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/error.o $(DEFAULT) -o $(TESTS_DIR)/bin/error

$(TESTS_DIR)/objects/forkrun.o: ./tests/functions/forkrun.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/forkrun.d -c ./tests/functions/forkrun.c -o $(TESTS_DIR)/objects/forkrun.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/forkrun.o $(DEFAULT) -o $(TESTS_DIR)/bin/forkrun

$(TESTS_DIR)/objects/new.o: ./tests/functions/new.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/new.d -c ./tests/functions/new.c -o $(TESTS_DIR)/objects/new.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/new.o $(DEFAULT) -o $(TESTS_DIR)/bin/new

$(TESTS_DIR)/objects/print.o: ./tests/functions/print.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/print.d -c ./tests/functions/print.c -o $(TESTS_DIR)/objects/print.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/print.o $(DEFAULT) -o $(TESTS_DIR)/bin/print

$(TESTS_DIR)/objects/range.o: ./tests/functions/range.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/range.d -c ./tests/functions/range.c -o $(TESTS_DIR)/objects/range.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/range.o $(DEFAULT) -o $(TESTS_DIR)/bin/range

$(TESTS_DIR)/objects/repeat.o: ./tests/functions/repeat.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/repeat.d -c ./tests/functions/repeat.c -o $(TESTS_DIR)/objects/repeat.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/repeat.o $(DEFAULT) -o $(TESTS_DIR)/bin/repeat

$(TESTS_DIR)/objects/warning.o: ./tests/functions/warning.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/warning.d -c ./tests/functions/warning.c -o $(TESTS_DIR)/objects/warning.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/warning.o $(DEFAULT) -o $(TESTS_DIR)/bin/warning

$(TESTS_DIR)/objects/any.o: ./tests/types/any.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/any.d -c ./tests/types/any.c -o $(TESTS_DIR)/objects/any.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/any.o $(DEFAULT) -o $(TESTS_DIR)/bin/any

$(TESTS_DIR)/objects/cstring.o: ./tests/types/cstring.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/cstring.d -c ./tests/types/cstring.c -o $(TESTS_DIR)/objects/cstring.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/cstring.o $(DEFAULT) -o $(TESTS_DIR)/bin/cstring

$(TESTS_DIR)/objects/framework.o: ./tests/types/framework.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/framework.d -c ./tests/types/framework.c -o $(TESTS_DIR)/objects/framework.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/framework.o $(DEFAULT) -o $(TESTS_DIR)/bin/framework

$(TESTS_DIR)/objects/map.o: ./tests/types/map.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/map.d -c ./tests/types/map.c -o $(TESTS_DIR)/objects/map.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/map.o $(DEFAULT) -o $(TESTS_DIR)/bin/map

$(TESTS_DIR)/objects/memtree.o: ./tests/types/memtree.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/memtree.d -c ./tests/types/memtree.c -o $(TESTS_DIR)/objects/memtree.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/memtree.o $(DEFAULT) -o $(TESTS_DIR)/bin/memtree

$(TESTS_DIR)/objects/string.o: ./tests/types/string.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/string.d -c ./tests/types/string.c -o $(TESTS_DIR)/objects/string.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/string.o $(DEFAULT) -o $(TESTS_DIR)/bin/string

$(TESTS_DIR)/objects/type.o: ./tests/types/type.c
	@$(CC) $(CFLAGS) $(CPATHS) -MMD -MF $(TESTS_DIR)/dependencies/type.d -c ./tests/types/type.c -o $(TESTS_DIR)/objects/type.o
	@$(CC) $(CFLAGS) $(CPATHS) $(TESTS_DIR)/objects/type.o $(DEFAULT) -o $(TESTS_DIR)/bin/type


